name: chassis_timeline_viewer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  collection: ^1.19.1
  lottie: ^3.3.2
  easy_localization: ^3.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  injectable: ^2.7.1+4
  get_it: ^9.2.1
  flutter_svg: ^2.2.4
  responsive_builder: ^0.7.1
  desktop_multi_window: ^0.3.0
  hive: ^2.2.3
  flutter_riverpod: ^2.6.1
  url_strategy: ^0.3.0
  hive_flutter: ^1.1.0
  display_metrics: ^2.3.0
  window_manager: ^0.5.1
  file_picker: ^11.0.2
  archive: ^4.0.9
  clipboard: ^3.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  build_runner: ^2.13.1
  json_serializable: ^6.13.1
  injectable_generator: ^2.12.1
  flutter_gen_runner: ^5.13.0+1
  lints: ^6.1.0

flutter_gen:
  output: lib/ui/utils/theme
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/
    - assets/fonts/
    - assets/svgs/
    - assets/lang/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/Instrument Sans/InstrumentSans-Bold.ttf
        - asset: assets/fonts/Instrument Sans/InstrumentSans-BoldItalic.ttf
        - asset: assets/fonts/Instrument Sans/InstrumentSans-Italic.ttf
        - asset: assets/fonts/Instrument Sans/InstrumentSans-Medium.ttf
        - asset: assets/fonts/Instrument Sans/InstrumentSans-MediumItalic.ttf
        - asset: assets/fonts/Instrument Sans/InstrumentSans-Regular.ttf
        - asset: assets/fonts/Instrument Sans/InstrumentSans-SemiBold.ttf
        - asset: assets/fonts/Instrument Sans/InstrumentSans-SemiBoldItalic.ttf
